
# This is a basic workflow to help you get started with Actions......
name: github-actions-selfhosted

# Controls when the action will run. 
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Setup java environment for the build
        uses: actions/setup-java@v1
        with:
          java-version: 14
      # Runs a single command using the runners shell
      - name: Run testcases
        run: mvn test
      
      - name: Package an artifact
        run: mvn package
        
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: Run sonarqube
        env:
          # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: sonar-scanner
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
             -Dsonar.organization=sriram9707
             -Dsonar.host.url=https://sonarcloud.io/
             -Dsonar.projectKey=sriram9707_Devops-Demo
          
      - name: Login to Artifactory
        run: docker login -u sriram9707 -p ${{ secrets.DOCKER_TOKEN}}
        
      - name: Create a docker image
        run: docker build -t sriram9707/spring-boot-example:1.0.${GITHUB_RUN_NUMBER} .
        
        
      - name: Push the docker image
        run: docker push sriram9707/spring-boot-example:1.0.${GITHUB_RUN_NUMBER}
      
      - name: Tag Git Repository
        run: git tag -a docker-release/v1.0.${GITHUB_RUN_NUMBER} -m "New Version"
        
      - name: Push Git tag
        run: git push origin docker-release/v1.0.${GITHUB_RUN_NUMBER}



